### ISSUE TITLE
Avoid page reload on server change

### ISSUE THREAD

**Issue by bdeterling** [szymmis/vite-express#115] opened 2024-01-25 20:25 UTC
Would it be possible to prevent server changes from doing a full page reload on the client? I've tested it with a fresh app created by create-vite-express. Nodemon is watching the server, so when the server code changes, it restarts, which is fine. But that also triggers the client to do a full page reload. If I'm deeply nested in the client UI trying to fix a server issue, I have to navigate back every time I change the server. 

Can/should that be addressed in this project, or should I just split the server into its own express app? Thanks in advance.

**Comment by szymmis** [comment] 2024-01-25 20:29
Hi @bdeterling, that's absolutely something that needs to be resolved in the templates themselves. It must be caused by misconfiguration of `nodemon` which results in watching all js/ts instead of just server folder. 

Can you tell me which template did you use?

**Comment by bdeterling** [comment] 2024-01-25 20:34
Ok, thanks for the quick response. I used create vite-express, fwiw.

**Comment by szymmis** [comment] 2024-01-25 20:36
The problem is, when nodemon shuts down your express site, Vite dev server is also shut down. That's why sockets for live-reload are destroyed and everything breaks.
If that's an issue for you then I believe having these two separate will help but at the same time you'll lose benefits of `vite-express`

**Closed** 2024-01-30 08:27 UTC
